spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    #url: jdbc:mysql://119.23.189.143:3306/henji?useUnicode=true&characterEncoding=utf-8&useSSL=false
    url: jdbc:mysql://47.107.105.43:3306/henji?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

management:
  endpoint:
    health:
      show-details: always

file-upload:
  base-url: http://127.0.0.1:8080/flexibleemployment-web/manage/file-upload/download?name=
  base-path: E:/fileUpload/
  attachment:
    ext-names: jpg,png,jpeg,doc,docx,xlsx,xls,pdf,zip,rar
    max-size: 10485760

wx:
  applet:
    wxAppid: wxcf77273f875cf9ce  #小程序45appid
    wxAppSecret: 0fd268a70bbaa3130303ae09113329c0 #小程序key
    pushUrl: https://api.weixin.qq.com/cgi-bin/message/wxopen/template/send?access_token=
    open-discern-order-url: /pages/identifyList/detail?id=  #跳转鉴定详情地址
    wxJscode2sessionApi: https://api.weixin.qq.com/sns/jscode2session?appid=%s&secret=%s&js_code=%s&grant_type=authorization_code
