spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://119.23.189.143:3306/henji?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

management:
  endpoint:
    health:
      show-details: always

file-upload:
  base-url: http://localhost:8089/flexibleemployment-web/
  base-path: D:/app1/imagedata/

  attachment:
    ext-names: jpg,png,jpeg,doc,docx,xlsx,xls,pdf,zip,rar
    max-size: 10485760

